apiVersion: v1
kind: Service
metadata:
  name: php
spec:
  selector:
    app: php
  ports:
  - port: 8080
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-connection
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
